version: 2
jobs:

  prepare_testing_machine:
      docker:
        - image: gopejavi/geb-spock-e2e
      environment:
          GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
          GRADLE_USER_HOME: .gradle-home
      steps:
        - checkout
        - restore_cache:
            keys:
              - gradle-home

  prepare_app:
      docker:
        - image: gopejavi/vokuro
      steps:
        - checkout

  test:
      steps:
        - run:
            command: |
              Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
              export DISPLAY=:99
              export FIREFOX_VERSION=56.0.1
              ./gradlew --info -P baseUrl=http://127.0.0.1 --no-daemon chromeHeadlessTest
        - store_artifacts:
            path: build/spock-reports
        - save_cache:
            key: gradle-home
            paths:
              - .gradle-home

workflows:
  version: 2
  build:
    jobs:
    - prepare_testing_machine
    - prepare_app
    - test:
        requires:
          - prepare_testing_machine
          - prepare_app